name: Release

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@00911586051618367fa9c19b161a0a146ac51970 # v2
        with:
          release-type: simple
